### ISSUE TITLE
Allyson Finck Cover Letter

### ISSUE THREAD

**Issue by allysonfinck** [ga-students/wdiroutcomes#131]
[IBM-cover-letter.pdf](https://github.com/ga-students/wdiroutcomes/files/1915318/IBM-cover-letter.pdf)

**Comment by nicoleump** [comment]
Great start, Allyson. However, although paragraph is strong, you didn't tell me what role you're applying to....

Then in paragraph two you immediately put yourself into the newbie category by mentioning that you recently completed the GA program. Reword the first sentence to something like "This year I added to my toolkit by focusing on web development, while building upon my previous design skills." From there, be specific in the languages or frameworks you're well versed in instead of being vague ["I have learned so many new programming languages (like JavaScript and Node) and techniques (Agile development) in the last few months...] 

Other than that, great job!
