### ISSUE TITLE
Rachel Elam-Brand Paragraph

### ISSUE THREAD

**Issue by relam24** [ga-students/wdiroutcomes#39]
Full stack web developer and musician who is driven by passion for creativity and intuitive content-design. Having a background in early-stage tech startups has given me the mindset to fail forward fast… taking risks for thoughtful, efficient solutions.

-I built this up from what we did in class below:
My five---
1. start-up/tech
2. entrepreneurial
3. introspection
4. music software
5. non-profit

My journey started with a huge focus on the non-profit sector which pushed me to obtain my bachelors degree in Nonprofit Administration. From there I ended up getting my first job doing sales for a well-known startup in the tech industry. Realizing my love for tech, I then went on to an early-stage startup where I was able to put processes and workflows in place that helped me understand what it takes to make a startup successful. Within those months, I had the opportunity to really focus on myself, and my need to create something that is my own.

**Comment by op9674a** [comment]
Great summary of your background, outside interest, and problem-solving approach!

**Comment by tnangel1984** [comment]
Great  work Rachel Iove how you were able to incorporate your role as  musician so seamlessly. I particularly like the "fail forward fast" reference have you been to startup weekend? That's their motto. 
You have a strong opening the delve into your story I like that you takes on your journey. My recommendation would be reduce/or eliminate some of the transition statements. For example in the second sentence you might just say:  My first job was in sales for a well-known startup in the tech industry. Otherwise great work I really enjoyed reading your statement and learning more about you!

**Comment by nataliewolff20** [comment]
I like how your statement is well-rounded but also specifically pointing you into start-up/ music / non-profit arenas.  You have a great idea of what you're looking for and also what you can bring to a company with your past experiences.
