### ISSUE TITLE
Erin McMackin - Final LinkedIn

### ISSUE THREAD

**Issue by erinmcmackin** [ga-students/wdiroutcomes#44]
https://www.linkedin.com/in/erinmcmackin/

**Comment by nicoleump** [comment]
Amazing job, Erin. Love the banner image! 

For GA in Experience, try removing and re-adding GA since the logo isn't showing correctly. 

Also (future reminder) don't forget about getting recommendations from classmates/instructors as well as former colleagues/managers as a way to build a more credible profile.
