### ISSUE TITLE
Victor Jaquez | Week 03 | HW

### ISSUE THREAD

**Issue by victorjaquez** [ga-students/wdiroutcomes#47]
https://www.linkedin.com/in/victorjaquez/

Draft: Focused on product development, innovation, and business strategy. With a mix of business and technology experience ranging from scaling an organization, business development, marketing and product management. Strong-willed with a team-mindset. Highly adaptable, with history of calculated risks with favorable results. I have a desire to build, matched by my desire to always continue to learn.

**Comment by nicoleump** [comment]
Feedback for your LinkedIn, Victor:
-Make sure to connect with me as that was part of the assignment.
-From there, where's your profile pic? [maybe I can't see it since we're not connected?] 
-For GA, try removing and re-adding GA so the logo shows correctly.
-turn off endorsements in the skills section so you have a nice clean list of skills
-get recommendations from classmates/instructors

**Comment by samwhindleton** [comment]
Feedback for brand statement.
Great at including everything you have to offer/bring to a team. I would try to expand on "I have a desire to build", if that includes web apps, databases, fullstack apps, etc. Overall this brand statement is great!

**Comment by awolfe89** [comment]
I really like your statement, I think it is well rounded & to the point. I liked this phrase a lot "I have a desire to build, matched by my desire to always continue to learn"
