### ISSUE TITLE
Alec Wilbur week 3 homework

### ISSUE THREAD

**Issue by lawilbur** [ga-students/wdiroutcomes#54]
https://www.linkedin.com/in/alec-wilbur/

Detailed planning is an important step in any major project but being flexible and having the ability to improvise are just as critical to ensure success. This attitude combine with excellent communication and a team oriented mindset are the keys to efficiently and effectively concur any task.

**Comment by nicoleump** [comment]
Feedback on your LinkedIn Profile is as follows:
-Connect with me (as that was part of the assignment)
-add your brand statement to your summary section one that's ready. 
-add links to your projects in the GA section in Experience
-get recommendations from classmates/instructors

**Comment by allysonfinck** [comment]
It's great how you efficiently hit on the five points while staying concise and tying it all together in the end! Just fix:
"attitude combined*"
"conquer* any task"

**Comment by swansavage** [comment]
Maybe include some more personal experiences/examples that reflect the statement. Maybe there is a past position of yours that highlights these ideas? Or how you personally apply this mindset in your work/life.

**Comment by TrentonMarks** [comment]
It's on a good route.  I think it might come off more powerful if instead of making it a 'general' statement, make it a statement about 'you'.  So the meat is great but just make it personal. 
Example: "I am a detailed planner that..."

**Comment by nicoleump** [comment]
Feedback on your brand statement (since we didn't get a chance to connect on this this week):

You have some great content but you need to rework it into a cohesive statement. Remember the four brand statement questions - what do you, what problem do you solve, how are you different, why should an employer care. You're currently answering questions 2,3,and 4 but you're missing the easy one - what do you do. Adding a sentence at the beginning "I am a web developer who is interested in..."will help answer that question. Then put everything together. Think about if a friend was pitching you to their boss - what would you want them to say about you?
