### ISSUE TITLE
Shaun Savage week 3 homework

### ISSUE THREAD

**Issue by swansavage** [ga-students/wdiroutcomes#55]
Brand Statement:
I am a self-starting, creative-minded web developer with a passion for user-focused design. My background as a full-time touring musician has positioned me to be an adaptable team player who can think on his feet and adjust plans quickly to overcome challenges with effective solutions.

LinkedIn profile:
https://www.linkedin.com/in/shaun-k-savage/

**Comment by nicoleump** [comment]
Feedback on your LinkedIn Profile:
-Add a link to your Github in the basic/summary section of your profile.
-For GA in Experience, try removing and re-adding GA so the logo shows correctly. Don't forget to add links to your projects as well. 
-get recommendations from classmates/instructor

**Comment by BrianMurphy89** [comment]
I think the brand statement could use a little more bulk to it. What I mean by that is show them what type of worker / team player they would be receiving in a corporate environment (or professional setting) - ultimately, what makes you different from every one else. Otherwise, I think it is great to highlight your previous experience, it gives you a unique quality that could stand out.

**Comment by lawilbur** [comment]
The only note I have would be rewording the 'creative-minded' phrase with something along the lines of inventive or innovative. Otherwise the rest of it sounds great.
