### ISSUE TITLE
Trenton Marks -- Brand Statement (Rough)

### ISSUE THREAD

**Issue by TrentonMarks** [ga-students/wdiroutcomes#57]
Top Five:
1) Entrepreneurial
2) Tech/ Startup
3) Restaurant Software
4) Passion for Innovation
5) Driven assertively

Statement:
I am a junior web developer in training with a heavy entrepreneurial mindset.  Through my past experience working in sales and restaurants, I have become aware of the incredible potential for tech startups within the restaurant software industry.  I have a great passion for innovation within this unique sub-industry.  I have shifted my drive to learning how to create software so that I don't miss out on the window of opportunity during this software-tech boom.

**Comment by tatewilson4** [comment]
This is looking good, I like how you added the top five key words. That will make it easy to add or change key words that a specific job may be looking for. Possibly add so that I can capitalize on the window of opportunity instead of miss out on. Maybe transform or transcend, or maybe in the end it sounds best the way it is. Just food for thought, this looks great though!

**Comment by BrianMurphy89** [comment]
I like how you said that the type of industry you want to go into. This does a great job of showing future employers that you have a pre-existing interest in this industry which could distinguish you from others. I would recommend removing the section of about not wanting to miss out on the tech boom, only because the people already in the industry know that and showing that you have an interest of breaking into the industry, shows you don't want to miss it either.
