### ISSUE TITLE
Teilachanell Brand Statement

### ISSUE THREAD

**Issue by tnangel1984** [ga-students/wdiroutcomes#62]
A multifaceted professional driven by a passion for learning, growth and development.  
My goal is to develop well rounded leadership capabilities that are easily translatable across industries. My future as I envision it would lie at the intersection of business, technology and social impact. As a consequence I am drawn to companies and organizations whose missions center on delivering a positive social impact; particularly those focused on reducing economic inequity.

Experienced in Marketing Management, FP&A and Programming, I have honed a holistic perspective backed by strong analytical skills. I enjoy working cross-functionally, coaching and developing teams, and working in collaborative environments to solve complex problems and deliver sustainable solutions.

https://www.linkedin.com/in/teilachanellangel/

**Comment by nicoleump** [comment]
For your LinkedIn: Thanks Teila. Make sure to connect with me as that was part of the assignment too. From there, my feedback is as follows:
-Add your Github profile url to your summary section.
-Since your role with Backyard Farms ended in November, I recommend you add a current role. Perhaps something like "Personal and Professional Gap Year" or what did you call it a Bucket Year? where you can talk about all the things you're doing in this time. 
-For your latest role with Pepsico, try removing and re-adding the company name so the logo shows correctly like the other one.
-Don't forget about getting recommendations as a way to build a more credible profile as well.

**Comment by erinmcmackin** [comment]
Love it! I like that you included your future vision, and especially how you positioned it with "at the intersection." The only thing I would change is to try to make it a little shorter if you can. People tend to stop reading after a few lines, and the second paragraph is so strong I wouldn't want them to miss it!

**Comment by tnangel1984** [comment]
Thanks Nicole, I had the git hub url on the summary but I removed it. I'd like to wait until I have some presentable projects in my portfolio to display before adding it back. I didn't want to attract attention to something that has little to show.  I made the other changes though  and will work on the reccomendations as well

**Comment by tnangel1984** [comment]
Thanks Erin that is great feedback, brevity is something I struggle with I'll work to merge the two paragraphs in the next iteration.
