### ISSUE TITLE
Rachel Elam- Week 4 Homework Rough Draft Resume

### ISSUE THREAD

**Issue by relam24** [ga-students/wdiroutcomes#63]
<img width="433" alt="resume ga" src="https://user-images.githubusercontent.com/24663859/37123771-65dbccd0-2233-11e8-8b21-8f8c6b6d4dbf.png">

**Comment by nicoleump** [comment]
Here's my feedback on your rough draft:
-As I mentioned on the call, this version is great when you are emailing someone directly. I recommend you have a simple no column resume so the applicant tracking system can read the content correctly. 
-In your Profile, capitalize Full Stack Web Developer since you're using it as a title. 
-I recommend you move Skills directly below your Profile section. 
-Don't forget to feature 2-3 projects in the GA section.
-In Education, remove the start year, keeping just 2015 (if at all).
