### ISSUE TITLE
Trenton Marks -- Resume (Rough)

### ISSUE THREAD

**Issue by TrentonMarks** [ga-students/wdiroutcomes#67]
[TrentonMarks_Resume.pdf](https://github.com/ga-students/wdiroutcomes/files/1804818/TrentonMarks_Resume.pdf)

**Comment by swansavage** [comment]
Great job, love the clean design and layout. Everything is very easy to find and the whole thing communicates well to the reader. Also like the choice of color in your name, a nice subtle pop.

 Not so much a critique as it is just a suggestion, but maybe try organizing your skills sections into front-end/back-end sections, as this may help emphasize your full-stack capabilities at first glance.

**Comment by lawilbur** [comment]
The layout is great but I might try to slime down the profile statement a little but overall it looks really good.

**Comment by nicoleump** [comment]
Feedback on your resume:
-Be consistent in your font size throughout your resume. Your contact info is really small and then your profile and skills section is larger. Be consistent.
-Add your Github profile url to your contact info section.
-Group your skills into categories so you're only using three lines instead of five.
-Feature 2-3 projects in the GA section in Experience.
-For Education, what did you study? Add the program here. If you only completed x amount of credits, add that. "Completed 30 credit hours in general education studies". 
-Remove start date, keeping just end date.
