### ISSUE TITLE
Olena Penn | Draft Resume

### ISSUE THREAD

**Issue by op9674a** [ga-students/wdiroutcomes#71]
https://drive.google.com/file/d/1vg5T0QY3H7moE7sTdGs4PF5wq87MJlfn/view?usp=sharing

Still needs cutting down - one part I definitely want to cut out will leave a chronological gap (2011-2013), so not sure what to do there/how much that matters.

**Comment by childofthe20th** [comment]
I would combine your first two entries at the top together and try and shorten the information a bit, especially your education formatting. Look for a template perhaps that spreads your info out so it's easier to read, and perhaps a little color too. Good job and keep up the awesomeness.

**Comment by nicoleump** [comment]
Resume Feedback:
-Add headline directly below your name.
-Add Github url to contact info. Make sure that link is hyperlinked. 
-LinkedIn url needs to be hyperlinked.
-Break up your web dev skills into separate categories, bolding the name of each category. Remove event planning since you're not focused on event planning jobs. 
-GA should not be its own section. Rename this section to Web Development Experience. Then move GA and title of Web Development Fellow with dates below that. Tighten that section up as you're currently wasting a lot of space.
-Education: add Web Development Immersive to GA
-Remove Awards from Education.
-Remove Activities and Interests from your resume altogether. 
-You need to get all the content onto one page so you may need to shrink the font size down a point or two.
