### ISSUE TITLE
allan wolfe resume rough draft 

### ISSUE THREAD

**Issue by awolfe89** [ga-students/wdiroutcomes#73]
https://docs.google.com/document/d/1KMtCoczZbwIES3Ypaw8QpKYAXiavUOgNvb2drwTN70U/edit?usp=sharing

**Comment by nicoleump** [comment]
The two-column resume is fine to use if you're emailing someone directly. But make sure to have a second version that can be read by the Applicant Tracking System.

Resume Feedback:
-As we discussed, remove your photo. 
-Add Github url to your contact info section.
-Skills should be listed above education. Flip those two.
-Remove the scales for skills and list the things out instead.
-The top header on the right side is using up a lot of space. Remove that since your name is on the left. Move your headline to the left as well.
-Make sure you are using evidence of impact for your role descriptions.
