### ISSUE TITLE
Shaun Savage - Week 4 - resume first draft

### ISSUE THREAD

**Issue by swansavage** [ga-students/wdiroutcomes#75]
https://docs.google.com/document/d/1LN9T-vlnoEv28Pbv4F4oYKJ9SlGaIyOieE2acuw8S-I/edit?usp=sharing

**Comment by TrentonMarks** [comment]
Content is much better than the layout/ format.  Add some color pop, get a good font style and size, put the skills bullet points into columns to compact it to a single page, and it'll look ready.  So literally just styling, which is greatest issue with mine as well.  I really like the way Rachel's looks as an example for great styling for a resume.

**Comment by lawilbur** [comment]
I like the layout because it is very straight forward but I might try to do something different with the skills section because it leaves a large open space on the right side. A splash of color could go a long way as well.

**Comment by nicoleump** [comment]
Resume Feedback:
-List your skills out using categories so you only take up 3 lines instead of 10+. Why are they underlined? 
-Make sure your dates align the at the same starting place all the way down the page.
-You'll have to tighten things up so everything fits nicely on one page. Play with font size and margins if needed.
