### ISSUE TITLE
Eric Sanchez Resume Draft

### ISSUE THREAD

**Issue by childofthe20th** [ga-students/wdiroutcomes#77]
https://drive.google.com/open?id=18-udAtVV6AqtAeXN2cck-Ncda4qq5n2K

**Comment by BrianMurphy89** [comment]
Resume looks good! One suggestion I would make is to shorten that first paragraph, you want to get the main points across quickly so they can progress through the resume to see the experience / skills they are looking for.

**Comment by TrentonMarks** [comment]
Love the 'color pop'.  The biggest improvement i think that could be made is to make certain key words stick out more.  At glance there isn't a whole lot of valuable information communicated without reading into the paragraphs.  This is the biggest problem with mine too so it won't be the greatest example.  I do think that Rachel's is a good example of what I'm trying to say.  Her font style and size make it hard to miss certain powerful key words on her resume.

**Comment by nicoleump** [comment]
Here's my feedback about your resume:
-Add your Github profile to your contact info section.
-Your profile is currently a list of skills rather than a brand statement. Rework this. 
-You need to add a current experience - GA, Web Development Fellow, like we talked about on the call. In this section you'll add a short description and feature 2-3 of your projects.
-Move the skills section up to directly below your profile section.
