### ISSUE TITLE
Trenton Marks -- Finals

### ISSUE THREAD

**Issue by TrentonMarks** [ga-students/wdiroutcomes#87]
LinkedIn:
https://www.linkedin.com/in/trentonmarks/

Resume: 
[Resume_TrentonMarks_WDI.pdf](https://github.com/ga-students/wdiroutcomes/files/1827843/Resume_TrentonMarks_WDI.pdf)

Brand Statement:
I am a full-stack web developer with a heavy entrepreneurial mindset.  As I have gained more and more work experience, I have become intrigued at the essential role that software plays in the success and growth of each industry.  Since I have first trained to understand basic business principles and the concepts behind driving consumers, I have a uniquely creative approach in the way that I develop software.  I am a self sufficient individual that has a clear understanding of the ultimate end-game of each company that I help in its advancement.

**Comment by nicoleump** [comment]
For your brand statement: I removed and reworked some wording below.

I am a full-stack web developer with a heavy entrepreneurial mindset. I am intrigued at the essential role that software plays in the success and growth of each industry. Since I have first trained to understand basic business principles and the concepts behind driving consumers, I have a uniquely creative approach in the way that I develop software. I am self-sufficient and strive to gain a clear understanding of the ultimate end-game of each company that I help in its advancement.
